### ISSUE TITLE
For backfilling: API will get 504 Gateway Time-out due to taking time to finish

### ISSUE THREAD

**Issue by huymq1710** [caoergou/airflow-extended-api-plugin#2]
The 504 Gateway Timeout error you're seeing is due to the server not getting a timely response from the Airflow backfill command. This is because the backfill operation takes time and doesn't instantly return a response.

Instead of waiting for the backfill operation to complete, I think we can return a response immediately to the client and let the operation continue in the background.

```python
    def _backfill(self):
        log.info("Extended API backfill called")

        body = request.get_json()
        try:
            command_list, username = backfillDAGRunSchema.load(body)
        except ValidationError as err:
            raise BadRequest(detail=str(err.messages))

        # For backfilling: API will get 504 Gateway Time-out due to taking time to finish
        # output = execute_cli_command(command_list, username)
        # result = commandExecutionResult.load(output)

        thread = threading.Thread(target=execute_cli_command, args=(command_list, username))
        thread.start()

        return {"message": "Backfill operation started"}, 202
```

**Comment by caoergou** [comment]
Perhaps you could consider submitting a PR and then we close the issue?

**Comment by huymq1710** [comment]
@caoergou 
PR submiited: https://github.com/caoergou/airflow-extended-api-plugin/pull/3
